---
# set a pause of time of 5 seconds to allow the proxysql container to start; defaults to 1
start_delay: 5

# logging level for the app. follows zerolog conventions; defaults to INFO
log_level: "DEBUG"

# proxysql admin configuration
proxysql:
  address: "127.0.0.1:6032"   # default: 127.0.0.1:6032
  username: "radmin"           # default: admin
  password: "radmin"        # default: NONE

# the mode in which the agent should run, if any. valid values: [core OR satellite], mutually exclusive, no default
# run_mode: core

# core mode specific configuratiobn
core:
  # number of seconds to pause in the loop. defaults to 10
  interval: 10
  # the path to the pod checksum file. defaults to /tmp/pods-cs.txt
  checksum_file: "/tmp/pods-cs.txt"
  # the k8s selector for the core pods
  pod_selector:
    # defaults to proxysql
    app: proxysql
    # defaults to core
    component: core

# satellite mode specific configuratiobn
satellite:
  # the number of seconds to pause in the loop. defaults to 10
  interval: 10

# valid values: [rest, socket]
interfaces:
- rest    # start the http rest interface
- socket  # start the unix socket interface
